### Listar denuncia
GET http://localhost:5104/api/denuncia/listar

### Cadastrar denuncia
POST http://localhost:5104/api/denuncia/cadastrar
Content-Type: application/json

{
  "Nome": "Jovens pegando fogo",
  "Descricao": "Jovens de 20 anos pegando fogo por conta de incendio",
  "Status": 1,
  "Rua": "Mato preto, 221",
  "Bairro": "Matinhos",
  "Cidade": "Caioba",
  "CategoriaDenunciaId": 3,
  "UsuarioId": 1
}

### Buscar denuncia
GET http://localhost:5104/api/denuncia/buscar/1